version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-sam-app-02"
s3_bucket = ""
s3_prefix = "my-sam-app-02"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
