version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1oy9r1k5atnob"
s3_prefix = "my-sam-app"
region = "us-east-1"
profile = "samblogpost"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
